---
title: "MATH 475. Applied Analytics Using SAS."
format: 
  html:
    toc: true
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

[Syllabus](syllabus.html)

| Date       | Section/Topic                     | Notes                                                                            | Assignments                                  |
|--------------|--------------|-----------------------------|---------------|
| **Week 1** |                                   |                                                                                  |                                              |
| 1/25       | Time Series: Moving Average       | [Note](slides/time_series_smoothing_ma.pdf)                                      |                                              |
| **Week 2** |                                   |                                                                                  |                                              |
| 1/30       |   Moving Avergae Smoothing                                | [Assignment 1's Note](assignments/assignment1_note.pdf)                          | [Assignment 1](assignments/assignment1.html) |
| 2/1        |  Exponential Smoothing                                 | [Slides](slides/time_series_smoothing_exponential.pdf), [note](slides/note2.pdf) | [Assignment 2](assignments/assignment2.html) |
| **Week 3** |                                   |                                                                                  |                                              |
| 2/6        |  Classical Decomposition                                 | [Note](slides/3_decomposition.pdf)                                               | [Assignment 3](assignments/assignment3.html) |
| 2/8        |  STL Decomposition                               | [Note](slides/4_decomposition_stl.pdf)                                           | [Assignment 4](assignments/assignment4.html) |
| **Week 4** |                                   |                                                                                  |                                              |
| 2/13       | Working on Assignments            |                                                                                  |                                              |
| 2/15       | Exponential Smoothing Forecasting | [Slides](slides/5.html)                                                          | [Assignment 5](assignments/assignment5.html) |
| **Week 5** |                                   |                                                                                  |                                              |
| 2/20       | White Noise and Random Walks            |                                                                                  |                                              |
| 2/22       | White Noise and Random Walks | [Slides](slides/6_wn_rw2.html)                                                          | [Assignment 6](assignments/assignment6.html) |
| **Week 6** |                                   |                                                                                  |                                              |
| 2/27       | White Noise and Random Walks           |                                                                                  |                                              |
| 2/29       | Auto-Regressive Models | [Slides](slides/7.html)                                                          | [Assignment 7](assignments/assignment7.html) |
| **Week 7** |                                   |                                                                                  |                                              |
| 3/5       | AR(p)           |  [Slides](slides/8.html)         |   [Assignment 8](assignments/assignment8.html)                                           |
| 3/7       | MA(q)      |   [Slides](slides/9.html)                                                        | [Assignment 9](assignments/assignment9.html)    |
| **Week 8** |  SPRING BREAK                                 |                                                                                  |                                              |
| **Week 9** |                                   |                                                                                  |                                              |
| 3/17       | ARIMA and SARIMA      | [Slides](slides/10_arima.html)     |  [Time Series Project](slides/project_ts.html)  |  
| 3/19       | Work on Project      |     |  [Time Series Project](slides/project_ts.html)  | 
| **Week 10** |                                   |                      |     |
| 3/25       | Time Series in SAS      |     |  [Assignment10](assignments/assignment10.html)  |  
| 3/27       | Text Mining      |  [Slides](slides/11_text.html), [Codes](assignments/assignment11_codes.html)   |  [Assignment 11](assignments/assignment11.html)  |  
| **Week 11** |                                   |                      |     |
| 4/2       |  Text Mining - Bigrams     |  [Codes](assignments/assignment12_codes.html)   |  [Assignment 12](assignments/assignment12.html)  | 
| 4/4       |  Text Mining - Correlations     |  [Codes](assignments/assignment13_codes.html)   |  [Assignment 13](assignments/assignment13.html)  | 
| **Week 12** |  
| 4/9       |  Text Mining - tf-idf     | [Slides](assignments/14_text_tfidf.html), [Notes](assignments/Analyzing frequency_ tf-idf.pdf), [Codes](assignments/assignment14_codes.html)   |  [Assignment 14](assignments/assignment14.html)|
| 4/11       |  Text Clustering     | [Codes](assignments/assignment15_codes2.html)   |  [Assignment 15](assignments/assignment15.html)  |
| **Week 13** |  
| 4/16       |  Topics Modeling   | [Slides](assignments/16_topic_modeling.html), [Codes](assignments/assignment16_codes2.html)   |  [Assignment 16](assignments/assignment16.html)|
| 4/18       |  Classification with Text Data   |  [Codes](assignments/assignment17_codes2.html)   |  [Assignment 17](assignments/assignment17.html)|
| **Week 14** |  
| 4/23       |  Text Mining in SAS   |    |  [Assignment 18](assignments/assignment18.html)|
| 4/25       |  Final Project   |    |  [Final Project](slides/project_text.html)|
: {.striped .hover}
