---
title: "MATH 475. Applied Analytics Using SAS."
format: 
  html:
    toc: true
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

[Syllabus](syllabus.html)

| Date | Section/Topic | Notes | Assignments |
|----------------|----------------|--------------------------|----------------|
| **Week 1** |  |  |  |
| 1/28 | Time Series: Moving Average       | [Note](slides/1_time_series_smoothing_ma.pdf)   | [Assignment 1](assignments/assignment1.html) |
| 1/30 | Exponential Smoothing |[Note](slides/2_time_series_smoothing_exponential.pdf)  | [Assignment 2](assignments/assignment2.html) |
| **Week 2** |  |  |  |
| 2/4        |  Classical Decomposition                                 | [Note](slides/4_decomposition_stl_2025.pdf)                                               | [Assignment 3](assignments/assignment3.html)  |
| 2/6        |  STL Decomposition                                 | [Note](slides/4_decomposition_stl_2025.pdf)                                               | [Assignment 4](assignments/assignment4.html)  |
| **Week 3** |                                   |                                                                                  |                                              |
| 2/11       | Exponential Smoothing Forecasting | [Slides](slides/5.html)                                                          | [Assignment 5](assignments/assignment5.html) |
| 2/13       | SAS: Exponential Smoothing Forecasting | [SAS Video](https://bryant.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d2ab7f3b-1a90-484f-8261-b283012f335c)                                                          | [Assignment 6](assignments/assignment6_2025.html) |
| **Week 4** |                                   |                                                                                  |                                              |
| 2/18       | White Noise and Random Walk |[Lecture Video](https://bryant.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=11fe3501-60f8-42ac-bd97-b288008cb96a), [Slides](slides/6_wn_rw2.html)                                                          | [Assignment 7](assignments/assignment7_2025.html) |
| 2/20       | Auto-Regressive Models | [Slides](slides/7.html)                                                          | [Assignment 8](assignments/assignment8_2025.html) |
| **Week 5** |                                   |                                                                        ||
| 2/25       | AR(p)           |  [Slides](slides/8.html)         |   [Assignment 9](assignments/assignment9_2025.html)                                           |
| 2/27       | ARIMA and SARIMA          | [MA(q)](slides/9.html), [ARIMA](slides/10_arima.html)  | [Time Series Project](slides/project_ts.html)                                             |
| **Week 6** | |||
| 3/4       | Time Series Project      |     |  [Time Series Project](slides/project_ts.html)  | 
| 3/6       | Project Presentation/Time Series in SAS      |     | [Assignment 10](assignments/assignment10.html) | 
| **Week 7** | SPRING BREAK |||
| **Week 8** | |||
| 3/18       | Time Series Project Presentation      |     |    | 
| 3/20      |  Tabular Data: Data Wrangling, <br> [Lecture Video](https://bryant.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=3e3b1e59-51ec-4163-b864-b2a60128f15e)      |     | [Assignment 11](assignments/assignment_tabular_1.html), <br> [Hospital Discharge Data](https://drive.google.com/drive/folders/15QNBf6YYKocK2nNIfpKDer58kQnCPNZJ?usp=sharing)   | 
| **Week 9** | |||
| 3/5       | Tabular Data Project      |     |  [Tabular Data Project](table_data_project.html)  | 
| 3/27       | Tabular Data Project      |     |  | 
| **Week 10** | |||
| 4/1       | Tabular Data Project Presentation     |     |    | 
| 4/3       | Text Mining      |  [Slides](slides/11_text.html), [Codes](assignments/assignment11_codes.html)   |  [Assignment 12](assignments/assignment12_2025.html)  |  
| **Week 11** | |||
| 4/8       |  Text Mining - Bigrams     |  [Codes](assignments/assignment12_codes.html)   |  [Assignment 13](assignments/assignment13_2025.html)  | 
| 4/10       |  Text Mining - Correlations     |  [Codes](assignments/assignment13_codes.html)   |  [Assignment 14](assignments/assignment14_2025.html)  | 
| **Week 12** | |||
| 4/15       |  Text Mining - tf-idf     | [Slides](assignments/14_text_tfidf.html), [Notes](assignments/Analyzing frequency_ tf-idf2.pdf), [Codes](assignments/assignment14_codes.html)   |  [Assignment 15](assignments/assignment15_2025.html)|
| 4/17       |  Text Clustering     | [Codes](assignments/assignment15_codes2.html)   |  [Assignment 16](assignments/assignment16_2025.html)  |
| **Week 13** |  
| 4/16       |  Topics Modeling   | [Slides](assignments/16_topic_modeling.html), [Codes](assignments/assignment16_codes2.html)   |  [Assignment 17](assignments/assignment17_2025.html)|
| 4/18       |  Classification with Text Data   |  [Codes](assignments/assignment17_codes2.html)   |  [Assignment 18](assignments/assignment18_2025.html)|
| **Week 14** |  
| 4/23       |  Text Mining in SAS   |    |  [Assignment 19](assignments/assignment19_2025.html)|
| 4/25       |  Final Project   |    |  [Final Project](slides/project_text.html)|
: {.striped .hover}


