---
title: "Text Mining 1"
format: html
editor: visual
---


```{r}
library(tidyverse)
library(tidytext)
df = read_csv('https://bryantstats.github.io/math475/assignments/netflix_titles.csv')
```
```{r}
# df$description
text <- c("Bryant University: A private university in Smithfield, Rhode Island! It has two colleges, the College of Arts and Sciences and the College of Business, and is accredited by the New England Commission of Higher Education")
text_df <- tibble(text = text)
text_df %>%
    unnest_tokens(word, text)

```


```{r}
get_stopwords()
```


```{r}
#f(x)

x = 10

# traditional way
sin(x)

# pipe operator
x %>% sin
```

```{r}
# traditional way
tan(log(abs(sin(cos(x)))))

# pipe 
x %>% 
  cos %>% 
  sin %>% 
  abs %>% 
  log %>% 
  tan


x1 = cos(x)
x2 = tan(x1)


```

# Bigrams

```{r}
library(tidyverse)
library(ggplot2)
library(tidytext)
df <- read_csv('https://bryantstats.github.io/math475/assignments/amazon_reviews.csv')
```


```{r}
# View(df)
df %>% 
  group_by(name) %>% 
  count(sort = TRUE)

```

